import turtle

wn=turtle.Screen()
wn.bgcolor("green")
alex=turtle.Turtle()
alex.color("blue")
alex.forward(75)
alex.left(90)
alex.forward(75)
alex.left(90)
alex.forward(75)
alex.left(90)
alex.forward(75)
wn=turtle.Screen()
pepu=turtle.Turtle()
pepu.shape("turtle")
pepu.color("brown")
pepu.speed(2)
pepu.forward(100)
pepu.left(45)
pepu.forward(100)
pepu.left(45)
pepu.forward(100)
wn.exitonclick()
